dotNet/sln/chleby.Web/Models/Trader.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace chleby.Web.Models
{
    public class Trader
    {
        public Trader()
        {
            Live = 1;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [Column("Name")]
        [Display(ResourceType = typeof(Resources.Strings), Name = "TraderPrimaryName")]
        public string PrimaryName { get; set; }

        [StringLength(100)]
        [Display(ResourceType = typeof(Resources.Strings), Name = "TraderTradingName")]
        public string TradingName { get; set; }

        public string Name { get { return string.IsNullOrWhiteSpace(TradingName) ? PrimaryName : TradingName; } }

        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(Resources.Strings), Name = "TraderTags")]
        public string Tags { get; set; } //NOTE!

        [Required]
        public int Live { get; set; }

        public virtual ICollection<Address> Address { get; set; }

        public virtual ICollection<TraderEmployee> Employees { get; set; }

        [Required]
        public int TypeId { get; set; }

        [ForeignKey("TypeId")]
        [Display(ResourceType = typeof(Resources.Strings), Name = "TraderType")]
        public virtual TraderType Type { get; set; }

        public virtual ICollection<TraderPrice> TraderPrices { get; set; }

        [Required]
        public int PayId { get; set; }

        [ForeignKey("PayId")]
        public virtual PaymentTerm PaymentTerms { get; set; }

        public override string ToString()
        {
            return string.Format("#{0} [{1}] {2}", Id, Name, Live == 1 ? "L" : Live == 2 ? "S" : "-");
        }
    }
}

dotNet/sln/chleby.Web/Models/TraderType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace chleby.Web.Models
{
    public class TraderType
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        //do uzgodnienia podczas tworzenia UI

        public virtual ICollection<Trader> Trader { get; set; }

        public virtual ICollection<TraderTypePrice> TraderTypePrices { get; set; } 

        public override string ToString()
        {
            return string.Format("#{0} {1}", Id, Name);
        }
    }
}

dotNet/sln/chleby.Web/Controllers/TradersController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using System.Web.UI;
using chleby.Web.Models;

namespace chleby.Web.Controllers
{
    //[ChlebyAuthorize(ReqRoles = RequiredRole.Employee)]
    [ChlebyModule("Customers", Parent = typeof(TurboTradersController))]
    [ChlebyMenu("CustomerList")]
    public class TradersController : MultiController
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            ViewBag.PossibleTypes = db.TraderTypes.ToList();
            ViewBag.PaymentT = db.PaymentTerms.ToList();
            ViewBag.users = Membership.GetAllUsers().Cast<MembershipUser>().ToDictionary(user => (Guid)user.ProviderUserKey, user => user.UserName);
            ViewBag.usedTraders = db.Invoices.Select(x => x.Trader.Id).Distinct().ToList();
        }

        public override dynamic InitData(RequestContext requestContext)
        {
            Initialize(requestContext);
            ViewBag.MyBusiness = HttpContext.Cache[requestContext.RouteData.Values["app"].ToString() + "__Business"];
            return new ComboViewModel<Trader>
            {
                Index = db.Traders.ToList(),
            };
        }

        // POST: /Traders/Create
        [NeedWrite]
        [HttpPost]
        public ActionResult Create(Trader trader)
        {
            if (ModelState.IsValid)
            {
                db.Traders.Add(trader);
                db.SaveChanges();
                //return RedirectToAction("Index", "TurboTraders");
                return RedirectToAction("SwitcherDone", "Internal", new { adminactor = trader.Id });
            }

            return MultiView(callbackModel: model => model.Create = trader);
        }

        //
        // GET: /Traders/Edit/5
        [NeedWrite]
        [OutputCache(Location = OutputCacheLocation.None)]
        public ActionResult Edit(int id)
        {
            Trader trader = db.Traders.Single(x => x.Id == id);
            return PartialView(trader);
        }

        [NeedWrite]
        [OutputCache(Location = OutputCacheLocation.None)]
        public ActionResult ToggleLive(int id, int live)
        {
            var trader = db.Traders.Find(id);
            if (trader == null)
                return Json(new { msg = "wrong id" }, JsonRequestBehavior.AllowGet);

            foreach (var emp in trader.Employees)
            {
                var user = Membership.GetUser(emp.ExternalAccountData);
                if (user != null)
                {
                    user.IsApproved = live == 1;
                    Membership.UpdateUser(user);
                }
            }
            trader.Live = live;

            try
            {
                db.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(new { msg = "db error - " + e.Message, value = trader.Live }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { msg = "ok", value = live }, JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /Traders/Edit/5
        [NeedWrite]
        [HttpPost]
        public ActionResult Edit(Trader trader)
        {
            trader.PaymentTerms = db.PaymentTerms.Find(trader.PayId);
            ModelState.Clear();
            TryValidateModel(trader);
            if (ModelState.IsValid)
            {
                db.Entry(trader).State = EntityState.Modified;
                db.SaveChanges();
                trader = db.Traders.Find(trader.Id);
                trader.Employees = db.TraderEmployees.Where(x => x.Id == trader.Id).ToList();                  
                foreach (var emp in trader.Employees)
                {
                    var user = Membership.GetUser(emp.ExternalAccountData);
                    if (user != null)
                    {
                        user.IsApproved = trader.Live == 1;
                        Membership.UpdateUser(user);
                    }   
                }
                return RedirectToAction("Index", "TurboTraders");
            }

            return MultiView(callbackModel: model => model.Edit = trader);
        }
        //
        // POST: /Traders/Delete/5
        [NeedWrite]
        public ActionResult Delete(int id)
        {
            var trader = db.Traders.Find(id);
            if (db.Invoices.Any(x => x.Trader.Id == id))
            {
                trader.Live = 0;
                db.SaveChanges();
                return RedirectToAction("Index", "TurboTraders");
            }

            foreach (var emp in trader.Employees)
            {
                var user = Membership.GetUser(emp.ExternalAccountData);
                if (user != null)
                    Membership.DeleteUser(user.UserName);
            }
            trader.Employees.ToList().ForEach(x => db.TraderEmployees.Remove(x));
            trader.Address.ToList().ForEach(x => db.Addresses.Remove(x));
            db.SnapshotOrderPositions.Where(x => x.Address.TraderId == id).ToList().ForEach(x => db.SnapshotOrderPositions.Remove(x));
            db.Prices.OfType<TraderPrice>().Where(x => x.TraderId == id).ToList().ForEach(x => db.Prices.Remove(x));
            db.Traders.Remove(trader);
            db.SaveChanges();
            return RedirectToAction("Index", "TurboTraders");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Import()
        {
            ViewBag.What = "customers";
            return PartialView();
        }

        [HttpPost]
        public ActionResult ImportFile(HttpPostedFileBase file)
        {
            var bytes = new byte[file.ContentLength];
            var ms = new MemoryStream(bytes);
            file.InputStream.CopyTo(ms);
            var str = Encoding.UTF8.GetString(bytes);
            return Import(str);
        }

        [HttpPost]
        public ActionResult Import(string csv, bool save = false)
        {
            ViewBag.csv = csv;
            ViewBag.What = "customers";

            var lines = new List<string>(csv.Split('\n'));
            if (lines.Count > 0)
                lines.RemoveAt(0);
            var errors = new List<Tuple<int, int, string>>();
            var curline = 0;
            var traders = new List<Trader>();
            var dbtraders = db.Traders.ToList().Select(x => x.Name).ToList();
            var types = new List<TraderType>();
            var terms = new List<PaymentTerm>();
            foreach (var tline in lines)
            {
                curline++;
                var line = tline.Trim();
                var fields = line.SplitCsv();
                var trader = new Trader();
                trader.Employees = new Collection<TraderEmployee>();
                trader.Address = new Collection<Address>();
                trader.Live = 1;
                if (fields.Length <= 1)
                    continue;
                if (fields.Length != 4)
                {
                    errors.Add(Tuple.Create(curline, -1, "wrong field count"));
                    continue;
                }

                if (string.IsNullOrWhiteSpace(fields[0]))
                {
                    errors.Add(Tuple.Create(curline, 1, "empty name"));
                    continue;
                }
                trader.PrimaryName = fields[0].Trim();
                if (traders.Any(i => i.Name == trader.Name) || dbtraders.Contains(trader.Name))
                {
                    //errors.Add(Tuple.Create(curline, 1, "name already used"));
                    //omijamy po cichu uzytego
                    continue;
                }

                trader.TradingName = fields[1].Trim();

                if (string.IsNullOrWhiteSpace(fields[2]))
                {
                    errors.Add(Tuple.Create(curline, 3, "empty type"));
                    continue;
                }

                var ttname = fields[2].Trim().Normalize(NormalizationForm.FormKD);
                var tt = db.TraderTypes.FirstOrDefault(x => x.Name == ttname);
                if (tt == null)
                {
                    tt = types.FirstOrDefault(x => x.Name.Equals(ttname, StringComparison.InvariantCultureIgnoreCase));
                    if (tt == null)
                    {
                        tt = new TraderType { Name = ttname };
                        types.Add(tt);
                    }
                }
                trader.Type = tt;

                if (string.IsNullOrWhiteSpace(fields[3]))
                {
                    errors.Add(Tuple.Create(curline, 4, "empty term"));
                    continue;
                }

                var ptname = fields[3].Trim().Normalize(NormalizationForm.FormKD);
                var pt = db.PaymentTerms.FirstOrDefault(x => x.Name == ptname);
                if (pt == null)
                {
                    pt = terms.FirstOrDefault(x => x.Name.Equals(ptname, StringComparison.InvariantCultureIgnoreCase));
                    if (pt == null)
                    {
                        pt = new PaymentTerm() { Name = ptname };
                        terms.Add(pt);
                    }
                }
                trader.PaymentTerms = pt;

                traders.Add(trader);
            }
            ViewBag.errors = errors;

            if (errors.Count == 0 && save)
            {
                types.ForEach(i => db.TraderTypes.Add(i));
                terms.ForEach(i => db.PaymentTerms.Add(i));
                traders.ForEach(i => db.Traders.Add(i));

dotNet/sln/chleby.Web/Views/Traders/Create.cshtml
@using System.Linq.Expressions
@model chleby.Web.Models.Trader

@{
    ViewBag.Title = Strings.Global_Create;
}

@using (Html.BeginForm("Create", "Traders", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        @Html.Hidden("Id", "0")
        @Helpers.GenerateEditorFor(Html, model => model.PrimaryName)
        @Helpers.GenerateEditorFor(Html, model => model.TradingName)
        @Helpers.GenerateEditorFor(Html, model => model.Tags)
        <div class="control-group">
            <div class="control-label">@Strings.Global_Status</div>
            <div class="controls">
                <label class="radio">
                    <input type="radio" name="Live" value="0">
                    @Strings.NotLive
                </label>
                <label class="radio">
                    <input type="radio" name="Live" checked value="1">
                    @Strings.Live
                </label>
                <label class="radio">
                    <input type="radio" name="Live" value="2">
                    @Strings.Traders_Sales_Lead
                </label>
            </div>
        </div>

        <div class="control-group">
            @Html.Label("Type", new { @class = "control-label" })
            <div class="controls">
                @{
    var selTT = ChlebyContext.ForCurrentApp().AppConfig.DefaultTTId;
    if (Model != null && Model.TypeId > 0) { selTT = Model.TypeId; }
                }
                @Html.RadioButtonForSelectList(model => model.TypeId,
                                                       ((IEnumerable<chleby.Web.Models.TraderType>)ViewBag.PossibleTypes)
                                                           .Select(option => new SelectListItem
                                                           {
                                                               Text = (option == null ? "None" : option.Name),
                                                               Value = option.Id.ToString(CultureInfo.InvariantCulture),
                                                               Selected = option.Id == selTT
                                                           }))
                @Html.ValidationMessageFor(model => model.TypeId)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.PaymentTerms, new { @class = "control-label" })
            <div class="controls">
                @{
    var selPT = ChlebyContext.ForCurrentApp().AppConfig.DefaultPTId;
    if (Model != null && Model.PayId > 0) { selPT = Model.PayId; }
                }
                @Html.RadioButtonForSelectList(model => model.PayId,
                        ((IEnumerable<PaymentTerm>)ViewBag.PaymentT)
                            .Select(option => new SelectListItem
                            {
                                Text = (option == null ? "None" : option.Name),
                                Value = option.Id.ToString(),
                                Selected = option.Id == selPT
                            }))
                @Html.ValidationMessageFor(model => model.PayId)
            </div>
        </div>
        @Helpers.ModalFormButtons()
    </fieldset>
}
@section Scripts {
    @Scripts.Render("~/js/jqueryval")
}

dotNet/sln/chleby.Web/Views/Traders/Edit.cshtml
@using System.Linq.Expressions
@using chleby.Web.Models
@using chleby.Web
@model chleby.Web.Models.Trader

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Traders", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        @Html.HiddenFor(model => model.Id)
        @Helpers.GenerateEditorFor(Html, model => model.PrimaryName)
        @Helpers.GenerateEditorFor(Html, model => model.TradingName)
        @Helpers.GenerateEditorFor(Html, model => model.Tags)
            <div class="control-group">
            <div class="control-label">Status</div>
            <div class="controls">
                <label class="radio">
                    <input type="radio" name="Live"@(Model.Live==0 ? "checked" : "") value="0">
                    Not Live
                </label>
                <label class="radio">
                    <input type="radio" name="Live" @(Model.Live==1 ? "checked" : "") value="1">
                    Live
                </label>
                <label class="radio">
                    <input type="radio" name="Live" @(Model.Live==2 ? "checked" : "") value="2">
                    Sales Lead
                </label>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">@Strings.Type</label>
            <div class="controls">
                @Html.RadioButtonForSelectList(model => model.TypeId,
                        ((IEnumerable<chleby.Web.Models.TraderType>)ViewBag.PossibleTypes)
                            .Select(option => new SelectListItem
                            {
                                Text = (option == null ? "None" : option.Name),
                                Value = option.Id.ToString(CultureInfo.InvariantCulture),
                                Selected = (Model != null) && (option.Id == Model.TypeId)
                            }))
                @Html.ValidationMessageFor(model => model.TypeId)
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">@Html.DisplayNameFor(model => model.PaymentTerms.Name)</label>
            <div class="controls">
                <select name="@Html.NameFor(model => model.PayId)" tabindex="7" class="autowidth">
                    @foreach (var pt in ViewBag.PaymentT)
                    {
                        if (pt.Id == Model.PaymentTerms.Id)
                        {
                        <option title="@pt.Name" value="@pt.Id" selected="selected">@pt.Name</option>
                        }
                        else
                        {
                        <option title="@pt.Name" value="@pt.Id">@pt.Name</option>
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.PayId)
            </div>
        </div>
         <div class="form-actions">
            <button class="btn btn-success" type="submit"><i class="icon-ok"></i>&nbsp;@Strings.Global_Save</button>
            <button type="button" class="btn btn-danger pull-right" data-dismiss="modal" ><i class="icon-remove-sign"></i>&nbsp;@Strings.Global_Cancel</button>
        </div>
    </fieldset>
}
@section Scripts {
    @Scripts.Render("~/js/jqueryval")
}